# .github/workflows/deploy.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-house-price-app:latest .
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-house-price-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.PRODUCTION_SERVER }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          password: ${{ secrets.PRODUCTION_SSH_PASSWORD }}  
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-house-price-app:latest
            docker stop fastapi_house_price_container || true
            docker rm fastapi_house_price_container || true
            docker run -d -p 8034:8034 --name fastapi_house_price_container ${{ secrets.DOCKER_USERNAME }}/fastapi-house-price-app:latest

