name: GitHub Actions Demo

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v2
        run: docker compose build ml_model
        run: docker tag ml_model ${{ secrets.DOCKER_USERNAME }}/monrepoondockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        run: docker push ${{ secrets.DOCKER_USERNAME }}/monrepoondockerhub
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PRODUCTION_SSH_USER }}@${{ secrets.PRODUCTION_SERVER }} \
            "docker compose pull ${{ secrets.DOCKER_USERNAME }}/monrepoondockerhub && \
            docker compose up -d ml_model"
        env:
          SSH_PASSWORD: ${{ secrets.PRODUCTION_SSH_PASSWORD }}

